<a href="https://colab.research.google.com/github/luanatocchio/tecprog1_Luana_Tocchio/blob/main/Lista_de_Exercicios_Numpy_Luana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

In [ ]:
import numpy as np

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [ ]:
arr = np.random.randint(1, 101, 100)
print(arr)
arrMax = arr.max()
arrMin = arr.min()
print(arrMax)
print(arrMin)

[ 39  59  57  33  38  72  53  96  96  42  16  86  50  26   6  97  46  84
  80  21  22  71  21  65  95  69  83  58  36  51  27  50  84  57  78  75
  21  99  85 100   4   8  15  80  87  28  83  45  86  61  50  77  30  18
  58   3  58  79  87   3  96  46  57  40  90  19   5  78  73  43   8  52
  97  19  89  82  92  18  73  73   9  27  26  48  37  84  45  61  92  38
  63  75  48  85  47  79  70  41  27  95]
100
3


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [ ]:
import numpy as np

In [ ]:
%%timeit 

def modulo(vetor):
  return (np.sum(vetor**2))**(1/2)

#dim = int(input('Qual a dimensão do vetor?'))
#vetor = np.random.randint(0,100,dim)

modulo(np.array([22, 70]))

25.3 µs ± 8.44 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%%timeit 
def modulo(vetor):
  modulo=((vetor*vetor).sum())**(1/2)
  return modulo

modulo(np.array([22, 70]))

13.9 µs ± 3.26 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%%timeit 
def modulo_vetor(arr):
  mod = np.sqrt((arr**2).sum())
  return mod

modulo_vetor(np.array([22, 70]))

10.8 µs ± 1.3 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
%%timeit 
def modulo_vetor(vetor):
    return np.linalg.norm(vetor)

modulo_vetor(np.array([22, 70]))

15.8 µs ± 5.63 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

```python

# dados dois arrays quaisquer de mesmo tamanho, a função deve retornar o EQM
y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

>>> 1.6666666666666665

```

In [ ]:
import numpy as np
def calculate_eqm(y_pred, y_i):
  dif_quad = (y_pred - y_i)**2
  EQM = dif_quad.sum()/y_pred.size
  return EQM

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [ ]:
arr = np.ones((3,3), dtype=int)
arr[1,1] = 0
print(arr)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [ ]:
def criar_matriz_bordada(linhas, colunas):
    dimensão = (linhas, colunas)
    matriz = np.zeros(dimensão)
    
    # Preenche as bordas da matriz com 1
    matriz[:, 0] = 1
    matriz[0, :] = 1
    matriz[-1, :] = 1
    matriz[:, -1] = 1
    
    return matriz

In [ ]:
criar_matriz_bordada(4,8)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

```python

# vamos supor uma matriz de entrada gerada por dados aleatórios
X = np.random.randn(64,512)
X.shape # apenas para verificar as dimensões
>>> (64, 512)

# a função deve executar a operação equacionada anteriormente, retornando uma nova matriz
X_processado = process_EEG_signal(X)
X_processado.shape
>>> (64, 512)

# Somando as diferenças entre cada elemento das duas matrizes, apenas para ilustrar que elas não são iguais
(X_processado - X).sum()
>>> -53.08727366483029

# Visualizando as matrizes, para verificar uma vez mais que, de fato, os elementos são diferentes
X
>>> array([[ 0.29305925,  0.89663038, -0.61032202, ..., -0.88086364,
        -0.8818789 ,  0.51260497],
       [-0.01274415,  1.05439522,  0.47958092, ..., -2.15387924,
         0.70721168,  0.97029889],
       [ 1.09478371, -0.16120847,  1.58400361, ...,  0.20981813,
         2.17373837,  0.94032162],
       ...,
       [-0.45294842, -2.28939505,  1.10111998, ...,  1.63581703,
        -0.39394924, -1.13400723],
       [-0.22669886,  0.25413429, -1.17870637, ..., -0.09509442,
         0.90733806,  0.37999411],
       [ 0.15476933, -0.03654717, -1.09982762, ...,  0.67600047,
        -0.84533328, -0.56433144]])

# Matriz após o processamento descrito no enunciado
X_processado

>>> array([[ 0.36713022,  0.85772513, -0.54902169, ..., -0.85626087,
        -0.97611435,  0.51718998],
       [ 0.06132682,  1.01548997,  0.54088126, ..., -2.12927647,
         0.61297623,  0.97488389],
       [ 1.16885469, -0.20011372,  1.64530394, ...,  0.23442091,
         2.07950292,  0.94490663],
       ...,
       [-0.37887744, -2.3283003 ,  1.16242031, ...,  1.6604198 ,
        -0.4881847 , -1.12942223],
       [-0.15262788,  0.21522904, -1.11740604, ..., -0.07049164,
         0.81310261,  0.38457911],
       [ 0.22884031, -0.07545242, -1.03852729, ...,  0.70060324,
        -0.93956874, -0.55974643]])

```

In [ ]:
# Solução

## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo do Limite Inferior (LI = Q1 - 1.5*IQR  ), ou acima do Limite Superior (LS = Q3 + 1.5*IQR).

![image.png](https://s3-sa-east-1.amazonaws.com/lcpi/0d8a7b04-b982-4e6b-9fc7-fbb062247d8d.png)


<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

```python
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

>>> array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])


# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

is_outlier
>>> array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

outliers_count
>>> 44

outliers
>>> array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

 ``` 

In [ ]:
# Solução

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [ ]:
arr = np.arange(1, 22, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21]


## Questão 9

Crie um array de 10 com valores aleatórios

In [ ]:
arr = np.random.rand(10)
print(arr)

[0.92084239 0.79119765 0.1232042  0.75891722 0.68307339 0.22713203
 0.17106554 0.98879217 0.84893387 0.11562155]


## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [ ]:
def normalizar(dados):
    
    media = np.mean(dados)
    desvio = np.std(dados)
    normalizados = (dados - media) / desvio
    
    return normalizados

In [ ]:
Inicio = 35
Fim = 10
arr = np.random.rand(100)*(Fim-Inicio) + Inicio
normalizado = normalizar(arr)
normalizado

array([ 0.02344397, -0.27096506, -0.15887826, -1.37564761, -0.31891533,
        0.4983186 , -1.53805197, -1.45269116,  0.13775084, -0.71075152,
        1.09465585, -1.49754987, -1.21296098, -1.12663194,  1.77106108,
        0.43457386,  0.52884843, -1.20831592, -1.29671582, -0.55299073,
       -1.75319182,  0.69330733,  0.12936065,  0.00819681,  0.4715353 ,
       -0.45125603, -1.24130616, -1.18560075,  1.68691995, -0.36214804,
       -0.72666924, -0.15303577,  1.14752866, -0.0888715 ,  1.26796842,
        1.77662919, -0.19419304,  0.37114182,  0.96907567,  1.06046231,
       -0.52633699, -0.28027311, -0.04638363, -1.35870535, -0.70377263,
        0.40042754,  1.45200297, -0.9841009 ,  1.11580882,  0.44938958,
       -1.4228486 , -1.68488031, -0.56838268,  1.14028568,  0.55412033,
        1.14862603,  1.21883915,  1.74932328,  1.63839803,  1.74377145,
        0.60717045, -1.73847011,  1.3832224 ,  0.68300112, -0.30631228,
        0.28783509, -0.787066  , -0.75014247,  0.23422399, -1.64

## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [ ]:
import numpy as np

def estatisticas_notas(notas):
    
    media = np.mean(notas)
    desvio = np.std(notas)
    notas_acima_7 = np.count_nonzero(notas > 7)
    reprovados = np.count_nonzero(notas < 5)
    menor_nota = np.min(notas)
    maior_nota = np.max(notas)
    
    return np.array([media, desvio, notas_acima_7, reprovados, menor_nota, maior_nota])

In [ ]:
estatisticas_notas(normalizado)

array([ 4.75175455e-16,  1.00000000e+00,  0.00000000e+00,  1.00000000e+02,
       -1.75319182e+00,  1.77662919e+00])